account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

codhc/urls.py
from django.urls import path, include
from . import views


app_name = 'codhc'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('addcomment', views.addcomment, name='addcomment'),
    path('add', views.addpost, name='addpost'),

    
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('codhc/', include('codhc.urls')),
]

sample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('codhc.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name='users'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.adduser, name='adduser'),
]

account/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    name = models.CharField(max_length=200)
    score = models.IntegerField(default=0)
    classyear = models.CharField(max_length=200)
    major = models.CharField(max_length=200)
    def __str__(self):
        return self.name

codhc/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.

#post class
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    post_text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True, null=True)
    def __str__(self):
        template = '{0.post_text}{0.user}{0.title}{0.pub_date}'
        return template.format(self)


#comment class
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True, null=True)
    def __str__(self):
        template = '{0.comment_text}{0.user}{0.post}{0.pub_date}'
        return template.format(self)

users/models.py
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.models import User
from django.db import models

codhc/forms.py
from django import forms
from django.forms import ModelForm
from codhc.models import Post, Comment

#Create the post form class
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['user']

#Create the cadet form class
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        #fields = '__all__'
        exclude = ['user']

users/forms.py
from django.contrib.auth.models import User
from django import forms

#create forms here

account/views.py
from django.http import HttpResponse, Http404
from django.contrib.auth.forms import UserCreationForm 
from django.urls import reverse_lazy, reverse
from django.views import generic 
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

class SignUp(generic.CreateView):
    from_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
    
def index(request):
    return render(request, 'account/login.html')

codhc/views.py
from django.shortcuts import render
from django.http import Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import Post, Comment
from .forms import PostForm, CommentForm
# Create your views here.

def index(request):
    latest_post_list = Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:10]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'codhc/index.html', context)

def detail(request, post_id):
    post = Post.objects.get(pk=post_id, pub_date__lte=timezone.now())
    comment_list = Comment.objects.filter(post=post_id).order_by('pub_date')[:10]
    return render(request, 'codhc/detail.html', {'post': post, 'comment_list':comment_list})

#add comment view for a seperate page
def addcomment(request):
    request.method = 'POST'
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            
            newcomment = form.save(commit=False)
            newcomment.user = request.user
            newcomment.save()
            return HttpResponseRedirect('/')
    else:
        form=CommentForm()
    return render(request, 'codhc/addcomment.html', {'form':form})

#addpost view for a seperate page
def addpost(request):
    request.method = 'POST'
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            newpost = form.save(commit = False)
            newpost.user = request.user
            newpost.save()
            
            return HttpResponseRedirect('/')
    else:
        form = PostForm()
    return render(request, 'codhc/addpost.html', {'form':form})


    

users/views.py
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.shortcuts import render
from django.template import loader

from django.http import HttpResponse
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    users = User.objects.all() #all django registered users
    context = {'users': users} #fill a context with the cadet list
    template = loader.get_template('users/index.html') #Get the template we created
    return HttpResponse(template.render(context, request)) #Render the template with the context

def adduser(request):
    form = UserCreationForm(request.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return HttpResponseRedirect('/users')
    return render(request, 'users/add.html', {'form': form})

account/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block content %}
    {%endblock %}
</body>
</html>

codhc/templates/codhc/addcomment.html
{% extends 'codhc/base_generic.html' %}
{% block comment_content %}

<form action="addcomment" method="post">
    {% csrf_token %}
    
    {% for field in form %}
    <div class="row">
        <div class="col-sm">    
            <b>{{ field.label_tag }}</b>
        </div>
        <div class="col-sm">
            {{ field }}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value="Submit" />
</form>

{% endblock %}

codhc/templates/codhc/addpost.html
{% extends 'codhc/base_generic.html' %}
{% block post_content %}

<form action="add" method="post">
    {% csrf_token %}
    
    {% for field in form %}
    <div class="row">
        <div class="col-sm">    
            <b>{{ field.label_tag }}</b>
        </div>
        <div class="col-sm">
            {{ field }}
        </div>
    </div>
    {% endfor %}

    <input type="submit" value="Submit" />
</form>

{% endblock %}

codhc/templates/codhc/base_generic.html
{% load static %}
<!DOCTYPE HTML>
<link rel="stylesheet" type="text/css" href="{% static 'codhc/style.css' %}">

<html>
    <head>
        <title>CODHC</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
      <div class="container">
        <h2>Call of Duty Honor Country</h2>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Contribute
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'codhc:index' %}">Home</a>
    <a class="dropdown-item" href="{% url 'codhc:addcomment' %}">Add Comment</a>
    <a class="dropdown-item" href="{% url 'codhc:addpost' %}">Add Post</a>
    <a class="dropdown-item" href="{% url 'users:index' %}">Login</a>
  </div>
</div>

<br />

    <div class="p-3 mb-2 bg-secondary text-white">
    {% block all_content %}
    {% endblock %}
    {% block post_content %}
    {% endblock %}
    {% block comment_content %}
    {% endblock %}
    </div>
</div>

</body>

codhc/templates/codhc/detail.html
{% load static %}
<!DOCTYPE HTML>
<link rel="stylesheet" type="text/css" href="{% static 'codhc/style.css' %}">

<html>
    <head>
        <title>CODHC</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
        <h2>Call of Duty Honor Country</h2>


<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Contribute
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'codhc:index' %}">Home</a>
    <a class="dropdown-item" href="{% url 'codhc:addcomment' %}">Add Comment</a>
    <a class="dropdown-item" href="{% url 'codhc:addpost' %}">Add Post</a>
    <a class="dropdown-item" href="{% url 'users:index' %}">Login</a>
  </div>
</div>


<h1>{{ post.title }}</h1>
<p>Posted by: {{ post.user }} (On: {{ post.pub_date }})</p>
<h3>{{ post.post_text }}</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<br></br>

{% block comment_content %}
<h4>Comments on this Post:</h4>
<a  href="{% url 'codhc:addcomment' %}"><button type="submit" name="button">Leave a Comment</button></a>
{% if comment_list %}
    <ul>
    {% for comment in comment_list %}
    <li>{{ comment.comment_text }}</li>
    <p> Posted by: {{ comment.user }} (On: {{ comment.pub_date }})</p> <br></br>  {% endfor %}
    </ul>
{% else %}
    <p>No comments are available.</p>
{% endif %}


{% endblock %}

codhc/templates/codhc/index.html
{% extends 'codhc/base_generic.html' %}
{% load static %}
{% block all_content %}

<link rel="stylesheet" type="text/css" href="{% static 'codhc/style.css' %}">
<h2>Post Dashboard</h2>
{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
    <li><a href="{% url 'codhc:detail' post.id %}">{{ post.title }}</a></li>    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

{% endblock %}

users/templates/users/add.html
{% extends 'users/base_generic.html' %}
{% block content %}
<form action="add" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

users/templates/users/base_generic.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Theory by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>CODHC - Login</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="{% url 'codhc:index' %}" class="logo">Home</a>
				</div>
			</header>

		<!-- Banner -->
			<section id="banner">
				<h1>Call of Duty Honor Country - Login</h1>
				<p>Log in or register a user account</p>
			</section>

		<!-- One -->
			<section id="one" class="wrapper">
				<div class="inner">
					<div class="flex flex-3">
						
						{% block content %}
				        {% endblock %}
					</div>
				</div>
			</section>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/skel.min.js" %}"></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

users/templates/users/index.html
{% extends 'users/base_generic.html' %}
{% block content %}
{% if user.is_authenticated %}
<p>Welcome, {{ user.get_username }}.  
<a href="{% url 'logout' %}">Log Out</a>
{% else %}
<a href="{% url 'login' %}">Log In</a>
{% endif %}
<p>
    
    
    {% if users %} <!-- check if list is full or empty -->
    <ul>
        <h3>User List:</h3>
      {% for user in users %}
          <li>{{ user }}</li>
      {% endfor %}
    
    </ul>
    {% else %}
    <p>No users in database</p>
    {% endif %}
    
    <a href="add">Add User Account</a>
    </p>
{% endblock %}